export class AdminFakeDb
{
    public static vehicles = [
            {
                "id"          : 1,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver1",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "4522567889",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8036",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 2,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver12",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GR",
                "Device"      : "56252544",
                "Make"        : "FORD",
                "Model"       : "AVALON",
                "VIN"         : "8036",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 3,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver3",
                "SubFleet"    : "Polarix Test",
                "Group"       : "FE",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8035",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 4,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver4",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8039",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 5,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver5",
                "SubFleet"    : "Polarix Test",
                "Group"       : "EW",
                "Device"      : "4358431347",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8033",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 6,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver1",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8036",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 7,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver12",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GR",
                "Device"      : "4234234341",
                "Make"        : "FORD",
                "Model"       : "AVALON",
                "VIN"         : "8036",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 8,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver7",
                "SubFleet"    : "Polarix Test",
                "Group"       : "FE",
                "Device"      : "45424524554",
                "Make"        : "Nissan",
                "Model"       : "AVALON",
                "VIN"         : "8035",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 9,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver3",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "4324",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 10,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver4",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8039",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 11,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver5",
                "SubFleet"    : "Polarix Test",
                "Group"       : "EW",
                "Device"      : "1231234134",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8033",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 12,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver1",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8036",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 13,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver12",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GR",
                "Device"      : "4234234341",
                "Make"        : "FORD",
                "Model"       : "AVALON",
                "VIN"         : "8036",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 14,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver3",
                "SubFleet"    : "Polarix Test",
                "Group"       : "FE",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8035",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 15,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver4",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8039",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 16,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver5",
                "SubFleet"    : "Polarix Test",
                "Group"       : "EW",
                "Device"      : "1231234134",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8033",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 17,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver3",
                "SubFleet"    : "Polarix Test",
                "Group"       : "FE",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8035",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 18,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver4",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8039",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 19,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver5",
                "SubFleet"    : "Polarix Test",
                "Group"       : "EW",
                "Device"      : "1231234134",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8033",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 20,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver1",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8036",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 21,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver12",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GR",
                "Device"      : "4234234341",
                "Make"        : "FORD",
                "Model"       : "AVALON",
                "VIN"         : "8036",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 22,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver3",
                "SubFleet"    : "Polarix Test",
                "Group"       : "FE",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8035",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 23,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver4",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8039",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 24,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver5",
                "SubFleet"    : "Polarix Test",
                "Group"       : "EW",
                "Device"      : "1231234134",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8033",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 25,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver4",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8039",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 26,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver5",
                "SubFleet"    : "Polarix Test",
                "Group"       : "EW",
                "Device"      : "1231234134",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8033",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 27,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver3",
                "SubFleet"    : "Polarix Test",
                "Group"       : "FE",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8035",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 28,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver4",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8039",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 29,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver5",
                "SubFleet"    : "Polarix Test",
                "Group"       : "EW",
                "Device"      : "1231234134",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8033",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 30,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver1",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8036",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 31,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver12",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GR",
                "Device"      : "4234234341",
                "Make"        : "FORD",
                "Model"       : "AVALON",
                "VIN"         : "8036",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 32,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver3",
                "SubFleet"    : "Polarix Test",
                "Group"       : "FE",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8035",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 33,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver4",
                "SubFleet"    : "Polarix Test",
                "Group"       : "GG",
                "Device"      : "45424524554",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8039",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            },
            {
                "id"          : 34,
                "unit"        : "AT09 Test TPMS",
                "Driver"      : "Driver5",
                "SubFleet"    : "Polarix Test",
                "Group"       : "EW",
                "Device"      : "1231234134",
                "Make"        : "TOYOTA",
                "Model"       : "AVALON",
                "VIN"         : "8033",
                "Plate"       : "USA-HGUE",
                "Last_Report" : "09/05/2017 09:50 am",
                "Location"    : "14433, Southwest 21st Street",
                "Status"      : "OK",
                "ServicePlan" : "Basic"
            }
        ]
    
    public static vehicle_detail_unit = [
        {
            'id' : 1,
            'name' : 'unit1'
        },
        {
            'id' : 2,
            'name' : 'unit2'
        },
        {
            'id' : 3,
            'name' : 'unit3'
        },
        {
            'id' : 4,
            'name' : 'unit4'
        },
        {
            'id' : 5,
            'name' : 'unit5'
        }
    ]
}
